# shellcheck shell=bash
# 外部 agent-skills の install/update/link/sync。common.sh の log/warn/make_symlink と DOTFILES_DIR に依存。

install_agent_skills() {
    local manifest="$DOTFILES_DIR/agent-skills.txt"
    [[ -f "$manifest" ]] || { warn "$manifest が無いため agent-skills インストールをスキップ"; return; }
    if ! command -v bunx >/dev/null 2>&1; then
        warn "bunx が無いため agent-skills インストールをスキップ"
        return
    fi

    log "agent-skills をインストール (bunx skills)"

    local line pkg skills_part
    while IFS= read -r line || [[ -n "$line" ]]; do
        line="${line%%#*}"
        line="${line#"${line%%[![:space:]]*}"}"
        line="${line%"${line##*[![:space:]]}"}"
        [[ -z "$line" ]] && continue

        if [[ "$line" == *"@"* ]]; then
            pkg="${line%%@*}"
            skills_part="${line#*@}"
        else
            pkg="$line"
            skills_part="*"
        fi

        log "  + $pkg (skills: $skills_part)"
        bunx skills add "$pkg" --skill "$skills_part" --agent universal --global -y \
            || warn "agent-skill '$line' のインストールに失敗"
    done < "$manifest"

    link_agent_skills
    sync_agent_skills_gitignore
}

# ~/.agents/skills/<name> を ~/.claude/skills/<name> と
# ~/.codex/skills/<name> に symlink。
# 既存の実体ディレクトリ（ユーザー自作 skill）は保護する。
link_agent_skills() {
    local src_root="$HOME/.agents/skills"
    [[ -d "$src_root" ]] || return

    local claude_dst="$HOME/.claude/skills"
    local codex_dst="$HOME/.codex/skills"
    mkdir -p "$claude_dst" "$codex_dst"

    local skill_dir name dst
    for skill_dir in "$src_root"/*/; do
        [[ -d "$skill_dir" ]] || continue
        name="$(basename "$skill_dir")"
        [[ "$name" == .* ]] && continue

        for dst in "$claude_dst/$name" "$codex_dst/$name"; do
            # 自作 skill (実ディレクトリ、または dotfiles を指す symlink) は保護。
            # 上書きしていいのは「存在しない」or「既に ~/.agents/skills/ を指す」場合のみ。
            if [[ -L "$dst" ]]; then
                local current
                current="$(readlink "$dst")"
                if [[ "$current" != "$src_root/$name" ]]; then
                    warn "$dst は既存リンク ($current) と衝突するため link をスキップ"
                    continue
                fi
            elif [[ -e "$dst" ]]; then
                warn "$dst は自作 skill と衝突するため link をスキップ"
                continue
            fi
            make_symlink "$dst" "$src_root/$name" >/dev/null || true
        done
    done
}

# ~/dotfiles/.claude/skills/.gitignore に外部 skill 名を書き出す。
# これらは ~/.agents/skills/ を指す symlink でマシン依存なので、
# git 追跡から外す。ユーザー自作 skill (既に tracked) は無影響。
sync_agent_skills_gitignore() {
    local src_root="$HOME/.agents/skills"
    local gitignore="$DOTFILES_DIR/.claude/skills/.gitignore"
    [[ -d "$src_root" ]] || return
    mkdir -p "$(dirname "$gitignore")"

    local tmp
    tmp="$(mktemp)"
    {
        echo "# Auto-generated by install_agent_skills — do not edit."
        echo "# 外部 agent-skills (~/.agents/skills/) への symlink 群。"
        local skill_dir name
        for skill_dir in "$src_root"/*/; do
            [[ -d "$skill_dir" ]] || continue
            name="$(basename "$skill_dir")"
            [[ "$name" == .* ]] && continue
            echo "/$name"
        done
    } > "$tmp"

    if ! cmp -s "$tmp" "$gitignore" 2>/dev/null; then
        mv "$tmp" "$gitignore"
        log "$gitignore を更新"
    else
        rm -f "$tmp"
    fi
}
update_agent_skills() {
    if ! command -v bunx >/dev/null 2>&1; then
        warn "bunx が無いため agent-skills 更新をスキップ"
        return
    fi
    log "agent-skills を更新 (bunx skills update -g -y)"
    bunx skills update -g -y || warn "agent-skills の update に失敗"
    link_agent_skills
    sync_agent_skills_gitignore
}
